spring.application.name=opsflow-backend
server.port=8080

spring.datasource.url=jdbc:mysql://127.0.0.1:3306/opsflow_db
spring.datasource.username=root
spring.datasource.password=Root@123


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
logging.level.org.springframework.security=TRACE
